### ISSUE TITLE
【优化建议】缓存与刷新

### ISSUE THREAD

**Issue by Xian0Grem** [CM-Edelweiss/nonebot-plugin-pmhelp#5]
web权限页面做个缓存,然后增一个刷新按钮
这样就不用每次点开都要加载很久

**Comment by CM-Edelweiss** [comment]
是登录页面还是登录后管理页面

**Comment by Xian0Grem** [comment]
登录后进行每个插件的权限管理页
![QQ20241028-155945](https://github.com/user-attachments/assets/2022c666-36fa-4130-ab41-d796140b371d)

**Comment by Xian0Grem** [comment]
另外我建议你把后台地址写进README里

**Comment by CM-Edelweiss** [comment]
> 登录后进行每个插件的权限管理页
> ![QQ20241028-155945](https://github.com/user-attachments/assets/2022c666-36fa-4130-ab41-d796140b371d)
> 

这个是nb获取群和用户信息导致的，要显示每个群里的每个人就比较慢了，加刷新按钮每次用还得重新获取(主要我不太会用amis)

**Comment by CM-Edelweiss** [comment]
> 另外我建议你把后台地址写进README里

也可以，启动时会打印web地址

**Comment by Xian0Grem** [comment]
> > 登录后进行每个插件的权限管理页
> > ![QQ20241028-155945](https://private-user-images.githubusercontent.com/65611818/380625054-2022c666-36fa-4130-ab41-d796140b371d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDMzMDksIm5iZiI6MTczMDEwMzAwOSwicGF0aCI6Ii82NTYxMTgxOC8zODA2MjUwNTQtMjAyMmM2NjYtMzZmYS00MTMwLWFiNDEtZDc5NjE0MGIzNzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA4MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MGZhZjliMGYzMTk3YzE2OGNhYTNjODEwMWNkNDYzZDhhMmQyODM1Y2M5OWYzMDRmNTdmMGI1M2M1MmQ1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K-vEmgLx-frJ3BaqJ3krbxqve1zSTMerK_yIAJ4ZYio)
> 
> 这个是nb获取群和用户信息导致的，要显示每个群里的每个人就比较慢了，加刷新按钮每次用还得重新获取(主要我不太会用amis)

我的意思是
在启动的时候获取一遍群和用户信息写进缓存里
进入权限管理面就读缓存就可以了
点击刷新按钮来重新获取群和用户信息

**Comment by CM-Edelweiss** [comment]
> > > 登录后进行每个插件的权限管理页
> > > ![QQ20241028-155945](https://private-user-images.githubusercontent.com/65611818/380625054-2022c666-36fa-4130-ab41-d796140b371d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDMzMDksIm5iZiI6MTczMDEwMzAwOSwicGF0aCI6Ii82NTYxMTgxOC8zODA2MjUwNTQtMjAyMmM2NjYtMzZmYS00MTMwLWFiNDEtZDc5NjE0MGIzNzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA4MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MGZhZjliMGYzMTk3YzE2OGNhYTNjODEwMWNkNDYzZDhhMmQyODM1Y2M5OWYzMDRmNTdmMGI1M2M1MmQ1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K-vEmgLx-frJ3BaqJ3krbxqve1zSTMerK_yIAJ4ZYio)
> > 
> > 这个是nb获取群和用户信息导致的，要显示每个群里的每个人就比较慢了，加刷新按钮每次用还得重新获取(主要我不太会用amis)
> 
> 我的意思是
> 在启动的时候获取一遍群和用户信息写进缓存里
> 进入权限管理面就读缓存就可以了
> 点击刷新按钮来重新获取群和用户信息

我可以写进文件里，web端加个按钮进行刷新🤔

**Comment by Xian0Grem** [comment]
> > > > 登录后进行每个插件的权限管理页
> > > > ![QQ20241028-155945](https://private-user-images.githubusercontent.com/65611818/380625054-2022c666-36fa-4130-ab41-d796140b371d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDMzMDksIm5iZiI6MTczMDEwMzAwOSwicGF0aCI6Ii82NTYxMTgxOC8zODA2MjUwNTQtMjAyMmM2NjYtMzZmYS00MTMwLWFiNDEtZDc5NjE0MGIzNzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA4MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MGZhZjliMGYzMTk3YzE2OGNhYTNjODEwMWNkNDYzZDhhMmQyODM1Y2M5OWYzMDRmNTdmMGI1M2M1MmQ1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K-vEmgLx-frJ3BaqJ3krbxqve1zSTMerK_yIAJ4ZYio)
> > > 
> > > 
> > > 这个是nb获取群和用户信息导致的，要显示每个群里的每个人就比较慢了，加刷新按钮每次用还得重新获取(主要我不太会用amis)
> > 
> > 
> > 我的意思是
> > 在启动的时候获取一遍群和用户信息写进缓存里
> > 进入权限管理面就读缓存就可以了
> > 点击刷新按钮来重新获取群和用户信息
> 
> 我可以写进文件里，web端加个按钮进行刷新🤔

好的好的😭，每次打开都要加载几十秒太蠢了

**Comment by CM-Edelweiss** [comment]
> > > > > 登录后进行每个插件的权限管理页
> > > > > ![QQ20241028-155945](https://private-user-images.githubusercontent.com/65611818/380625054-2022c666-36fa-4130-ab41-d796140b371d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDMzMDksIm5iZiI6MTczMDEwMzAwOSwicGF0aCI6Ii82NTYxMTgxOC8zODA2MjUwNTQtMjAyMmM2NjYtMzZmYS00MTMwLWFiNDEtZDc5NjE0MGIzNzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA4MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MGZhZjliMGYzMTk3YzE2OGNhYTNjODEwMWNkNDYzZDhhMmQyODM1Y2M5OWYzMDRmNTdmMGI1M2M1MmQ1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K-vEmgLx-frJ3BaqJ3krbxqve1zSTMerK_yIAJ4ZYio)
> > > > 
> > > > 
> > > > 这个是nb获取群和用户信息导致的，要显示每个群里的每个人就比较慢了，加刷新按钮每次用还得重新获取(主要我不太会用amis)
> > > 
> > > 
> > > 我的意思是
> > > 在启动的时候获取一遍群和用户信息写进缓存里
> > > 进入权限管理面就读缓存就可以了
> > > 点击刷新按钮来重新获取群和用户信息
> > 
> > 我可以写进文件里，web端加个按钮进行刷新🤔
> 
> 好的好的😭，每次打开都要加载几十秒太蠢了

我现在在研究怎么把限流写进web，amis用不太明白(
