### ISSUE TITLE
【功能建议】菜单太长的问题 添加超级用户菜单 Emoji字体的支持

### ISSUE THREAD

**Issue by yasdiox** [CM-Edelweiss/nonebot-plugin-pmhelp#9]
插件多了帮助图片会变成超长一条，希望能提供压缩的功能。
例如添加子菜单：在主菜单只显示插件名，通过`/help 插件名`来显示详细功能。
或者添加多列显示。

希望能添加超级用户菜单，
用以显示所有被设置为需要超级用户权限才能使用的指令。

希望菜单能支持Emoji

以及用[htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)渲染帮助菜单是否会更好一点？
最后希望pmhelp成长为nonebot最强大的插件管理器。

**Comment by CM-Edelweiss** [comment]
感谢！
功能会考虑的，但用[htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)会占用大量内存，暂时不考虑使用htmlrender

**Comment by CM-Edelweiss** [comment]
1.现在可以开启分片模式，单独发`help`只会发送插件的名字，发送`help 帮助名1 帮助名2`可以选择发送详细帮助。

2.一些插件或者指令只有`超级用户`发送时才完整的显示出来。

*可能要重新生成yml文件(也可能不用)

**Comment by yasdiox** [comment]
十分感谢
另外确实需要重新生成 否则webui确认时会出现接口报错
![PixPin_2024-12-09_08-52-16](https://github.com/user-attachments/assets/2fac0b80-25da-42e8-8640-257ff10ce4c5)

**Comment by CM-Edelweiss** [comment]
> 分片模式排版还是有点反人类（
> 是否可以调整成：
> 
> - 蓝色部分为插件分类
> - 绿色部分为插件名
> - 黄色部分为插件描述(description)
> 
> ![PixPin_2024-12-09_12-45-08](https://github.com/user-attachments/assets/b068e625-a10e-485b-bd02-a590229dec2c)
> 
> 在一个分类内的卡片展示插件的同时提供描述
> 
> 

你可以单独开一个格子放简介

**Comment by yasdiox** [comment]
好的
感谢你的更新
